language: go
sudo: false

matrix:
  include:
  - go: tip
  allow_failures:
  - go: tip

script:
- "./build-all"
- go get golang.org/x/tools/cmd/cover
- go test -coverprofile fmt

deploy:
  provider: releases
  api_key:
    secure: YLMHytiiU4f0xiYajEidDMKJrGQZIcBD+NiuyjhO7r4egr7FyzwI0la05yP1eOukJGTTrU/SWCKOxP+Avy9xxGr1Kn0Mq4nHNeSH8FcyK7R5PgBdMM1EyEqa9iXDQVwDAMmFkvu4/JY/wBEvfSKuKSGrzinF/SGzkSf7pcDY+9dWzG+UdxLwQFLEvN9cG2cH1elMIqFlNV30NZM1iCzsbt0rR3zWWcolLMF+CSQTQobx0a5Qxs/auDdvQMYlK7xz4jNVn0g4X7V5J4O+6LtAgMR7wKm2wQgImFJMfPkuiYILIv/e/UANObq3QYc4Da2qRBv5ybNsPH/bAchj/3bQ4iiXaNYTJU2lMCumpH+qazpXBrCxsTwSMkgbleKUGq/sfJOQvzTjLCMOvJ+PJONomsDALazrHRqYhzRZ1W3KKtb/caStIhArfl5QUUKd/QRo2OI7Q25ZmOmjM0byPfly9fqJuQoBtGXmRhjXkdk2jt0ceb25AucVhDD8+0rJUFLNapj8GXwelEr00bTSrX3XQwsvUGZiAKPljkAY45xhsMm9jBxOrMMGVp77XyIXuyrAq2LRMLhKkRU2sSdjTbjXz/dgkO8NNRDlxg25yFZO5tC1RnAWVZ9Zx9rBTvUQ2VCIhMBhiZGHUHRasIl4EiUXmvf8ZYd0eVEFy/N8FzBEdv4=
  file_glob: true
  file: dns-api-go*
  on:
    tags: true
